export const ROUTES = {
  LOGIN: '/login',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  DASHBOARD: '/dashboard',
  COURSES: '/courses',
  COURSE_DETAIL: (id: string) => `/courses/${id}`,
  COURSE_EDITOR: (id: string) => `/courses/${id}/edit`,
  LESSON: (courseId: string, lessonId: string) => `/courses/${courseId}/lessons/${lessonId}`,
  QUIZ_BUILDER: (courseId: string, quizId: string) => `/courses/${courseId}/quizzes/${quizId}/build`,
  QUIZ_SUBMISSIONS: (courseId: string, quizId: string) => `/courses/${courseId}/quizzes/${quizId}/submissions`,
  QUIZ_TAKE: (quizId: string) => `/quizzes/${quizId}/take`,
  SUBMISSION: (submissionId: string) => `/submissions/${submissionId}`,
  GRADEBOOK: (courseId: string) => `/courses/${courseId}/gradebook`,
  MY_GRADES: '/grades',
  ATTENDANCE: '/attendance',
  COURSE_ATTENDANCE: (id: string) => `/courses/${id}/attendance`,
  COURSE_ATTENDANCE_REPORT: (id: string) => `/courses/${id}/attendance/report`,
  ANALYTICS: '/analytics',
  TEACHER_ATTENDANCE: '/teacher/attendance',
  MY_STUDENTS: '/teacher/students',
  GAMIFICATION: '/gamification',
  PARENT_DASHBOARD: '/parent',
  ADMIN_USERS: '/admin/users',
  ADMIN_REPORTS: '/admin/reports',
  ADMIN_SETTINGS: '/admin/settings',
  PARENT: '/parent',
  PARENT_CHILD: (id: string) => `/parent/children/${id}`,
  PARENT_CHILD_GRADES: (id: string) => `/parent/children/${id}/grades`,
  PARENT_CHILD_ATTENDANCE: (id: string) => `/parent/children/${id}/attendance`,
  FORBIDDEN: '/403',
  NOT_FOUND: '/404',
} as const
