"""Add parent-child relationship support

Revision ID: add_parent_child_relationships
Revises: 32bb53b5b461
Create Date: 2026-04-21

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'add_parent_child_relationships'
down_revision: Union[str, None] = '32bb53b5b461'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create parent_child_relationships lookup table
    op.create_table(
        'parent_child_relationships',
        sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.Column('description', sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )

    # Insert default relationship types
    op.bulk_insert(
        sa.table(
            'parent_child_relationships',
            sa.column('id', sa.SmallInteger),
            sa.column('name', sa.String),
            sa.column('description', sa.String)
        ),
        [
            {'id': 1, 'name': 'mother', 'description': 'Biological or adoptive mother'},
            {'id': 2, 'name': 'father', 'description': 'Biological or adoptive father'},
            {'id': 3, 'name': 'guardian', 'description': 'Legal guardian'},
            {'id': 4, 'name': 'step_parent', 'description': 'Step-parent'},
            {'id': 5, 'name': 'grandparent', 'description': 'Grandparent'},
            {'id': 6, 'name': 'other', 'description': 'Other family member or caregiver'},
        ]
    )

    # Create parent_child_links junction table
    op.create_table(
        'parent_child_links',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('parent_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('student_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('relationship_id', sa.SmallInteger(), nullable=False),
        sa.Column('is_primary_contact', sa.Boolean(), nullable=False, server_default='false'),
        sa.ForeignKeyConstraint(['parent_id'], ['users.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['relationship_id'], ['parent_child_relationships.id'], ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('parent_id', 'student_id', name='uq_parent_student')
    )
    op.create_index('idx_parent_child_parent_id', 'parent_child_links', ['parent_id'])
    op.create_index('idx_parent_child_student_id', 'parent_child_links', ['student_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_parent_child_student_id', table_name='parent_child_links')
    op.drop_index('idx_parent_child_parent_id', table_name='parent_child_links')
    op.drop_table('parent_child_links')
    op.drop_table('parent_child_relationships')
    # ### end Alembic commands ###
